#Below used for testing for picking config from git
#spring:
  #application:
    #name: USER-DEFAULT-CONFIG
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url.defaultZone: http://localhost:8761/eureka
